version: '3.8'

services:
  web:
    build:
      context: ./our_app
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/our_app/web/staticfiles
    expose:
      - 8000
   
    
        
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/our_app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  
  static_volume: